version: 2
jobs:
  build:
    working_directory: ~
    # The primary container is an instance of the first image listed. The job's commands run in this container.
    docker:
      - image: circleci/openjdk:11-jdk-stretch
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "pom.xml" }}

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test:
          requires:
            - build
          filters:
            branches:
              only: master