version: 2.1

orbs:
  openjdk-install: cloudesire/openjdk-install@1.2.3
  maven: circleci/maven@0.0.12

workflows:
  maven_test:
    jobs:
      - maven/test # checkout, build, test, and upload test results